command_timeout = 2000
add_newline = false

[character]
success_symbol = 'ğŸŸ¢'
error_symbol = 'ğŸ”´'
vimcmd_symbol = 'ğŸŸ¡'
vimcmd_replace_one_symbol = 'ğŸ”µ'
vimcmd_replace_symbol = 'ğŸ”µ'
vimcmd_visual_symbol = 'ğŸŸ£'

[aws]
disabled = true

[gcloud]
disabled = true

[time]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 8

[hostname]
disabled = true

[nodejs]
symbol = 'ğŸŸ©'

[golang]
symbol = 'ğŸ€'
format = 'via [$symbol($version )($mod_version )]($style)'

[battery]
disabled = true

[git_status]
conflicted = 'ğŸš©'
ahead = 'ğŸ’¨'
behind = 'â©'
diverged = 'ğŸ˜µ'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ’¥'

[shell]
fish_indicator = 'ğŸ¦ˆ'
bash_indicator = 'ğŸ’²'
powershell_indicator = 'ğŸ’ª'
unknown_indicator = 'ğŸ’»'
disabled = false
