[tools]
bun = "latest"
go = "latest"
"go:github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen" = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:autocannon" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:nodemon" = "latest"
"npm:npm-check-updates" = "latest"
"npm:prettier" = "latest"
python = "latest"
rust = "latest"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
